language: node_js
before_script: 
  - curl https://raw.githubusercontent.com/shapesecurity/CLA/master/cla-travis.sh | bash
script:
  - npm run build
  - git diff-index --quiet --cached HEAD
  - npm run generate-coverage
  - npm run check-coverage
node_js:
  - "0.11"
  - "0.10"
